package com.dhh.landservices;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class LandServiceWorkflowModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Decision")
	private java.lang.String is_approved;

	@org.kie.api.definition.type.Label("Transaction")
	private com.dhh.landservices.Transaction transaction;

	@org.kie.api.definition.type.Label("Payment 1")
	private java.lang.String is_payment1_paid;

	@org.kie.api.definition.type.Label("Payment 2")
	private java.lang.String is_payment2_paid;

	@org.kie.api.definition.type.Label("Payment 3")
	private java.lang.String is_payment3_paid;

	public LandServiceWorkflowModel() {
	}

	public java.lang.String getIs_approved() {
		return this.is_approved;
	}

	public void setIs_approved(java.lang.String is_approved) {
		this.is_approved = is_approved;
	}

	public com.dhh.landservices.Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(com.dhh.landservices.Transaction transaction) {
		this.transaction = transaction;
	}

	@Override
	public String toString() {
		return "LandServiceWorkflowModel [is_approved=" + is_approved
				+ ", transaction=" + transaction + "]";
	}

	public java.lang.String getIs_payment1_paid() {
		return this.is_payment1_paid;
	}

	public void setIs_payment1_paid(java.lang.String is_payment1_paid) {
		this.is_payment1_paid = is_payment1_paid;
	}

	public java.lang.String getIs_payment2_paid() {
		return this.is_payment2_paid;
	}

	public void setIs_payment2_paid(java.lang.String is_payment2_paid) {
		this.is_payment2_paid = is_payment2_paid;
	}

	public java.lang.String getIs_payment3_paid() {
		return this.is_payment3_paid;
	}

	public void setIs_payment3_paid(java.lang.String is_payment3_paid) {
		this.is_payment3_paid = is_payment3_paid;
	}

	public LandServiceWorkflowModel(java.lang.String is_approved,
			com.dhh.landservices.Transaction transaction,
			java.lang.String is_payment1_paid,
			java.lang.String is_payment2_paid, java.lang.String is_payment3_paid) {
		this.is_approved = is_approved;
		this.transaction = transaction;
		this.is_payment1_paid = is_payment1_paid;
		this.is_payment2_paid = is_payment2_paid;
		this.is_payment3_paid = is_payment3_paid;
	}
}