package com.dhh.landservices;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Notary implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String first_name;
	private java.lang.String second_name;
	private java.lang.String third_name;
	private java.lang.String fourth_name;
	private java.lang.String address;
	private java.lang.String contact_number;
	private java.lang.String email;
	private java.util.Date updated_at;
	private java.util.List<java.lang.String> user;

	private java.util.Date created_at;

	public Notary() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFirst_name() {
		return this.first_name;
	}

	public void setFirst_name(java.lang.String first_name) {
		this.first_name = first_name;
	}

	public java.lang.String getSecond_name() {
		return this.second_name;
	}

	public void setSecond_name(java.lang.String second_name) {
		this.second_name = second_name;
	}

	public java.lang.String getThird_name() {
		return this.third_name;
	}

	public void setThird_name(java.lang.String third_name) {
		this.third_name = third_name;
	}

	public java.lang.String getFourth_name() {
		return this.fourth_name;
	}

	public void setFourth_name(java.lang.String fourth_name) {
		this.fourth_name = fourth_name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getContact_number() {
		return this.contact_number;
	}

	public void setContact_number(java.lang.String contact_number) {
		this.contact_number = contact_number;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.util.Date getUpdated_at() {
		return this.updated_at;
	}

	public void setUpdated_at(java.util.Date updated_at) {
		this.updated_at = updated_at;
	}

	public java.util.List<java.lang.String> getUser() {
		return this.user;
	}

	public void setUser(java.util.List<java.lang.String> user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Notary [id=" + id + ", first_name=" + first_name
				+ ", second_name=" + second_name + ", third_name=" + third_name
				+ ", fourth_name=" + fourth_name + ", address=" + address
				+ ", contact_number=" + contact_number + ", email=" + email
				+ ", updated_at=" + updated_at + ", user=" + user + ", created_at=" + created_at + "]";
	}

	public java.util.Date getCreated_at() {
		return this.created_at;
	}

	public void setCreated_at(java.util.Date created_at) {
		this.created_at = created_at;
	}

	public Notary(java.lang.Long id, java.lang.String first_name,
			java.lang.String second_name, java.lang.String third_name,
			java.lang.String fourth_name, java.lang.String address,
			java.lang.String contact_number, java.lang.String email,
			java.util.Date updated_at, java.util.List<java.lang.String> user,
			java.util.Date created_at) {
		this.id = id;
		this.first_name = first_name;
		this.second_name = second_name;
		this.third_name = third_name;
		this.fourth_name = fourth_name;
		this.address = address;
		this.contact_number = contact_number;
		this.email = email;
		this.updated_at = updated_at;
		this.user = user;
		this.created_at = created_at;
	}

}