package com.dhh.landservices;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@JsonIgnoreProperties(ignoreUnknown = true)
public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Service Id")
	private java.lang.Integer service_id;

	@org.kie.api.definition.type.Label("Application Date")
	private java.util.Date application_date;

	@org.kie.api.definition.type.Label("Settlement Amount")
	private java.math.BigDecimal settlement_amount;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("Workflow Status")
	private java.lang.String workflow_status;

	@org.kie.api.definition.type.Label("Buyer Id")
	private java.lang.Long buyer_id;

	@org.kie.api.definition.type.Label("Seller Id")
	private java.lang.Long seller_id;

	@org.kie.api.definition.type.Label("Property Id")
	private java.lang.Long property_id;

	@org.kie.api.definition.type.Label("Notary Id")
	private java.lang.Long notary_id;

	@org.kie.api.definition.type.Label("Payment Status")
	private java.lang.String payment_status;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TRANSACTION_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "TRANSACTION_ID_SEQ", name = "TRANSACTION_ID_GENERATOR")
	@org.kie.api.definition.type.Label("Transaction Id")
	private java.lang.Long id;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Notary")
	@JsonProperty("notary")
	private com.dhh.landservices.Notary notary;

	@org.kie.api.definition.type.Label(value = "Settlement Date")
	private java.util.Date settlement_date;

	public Transaction() {
	}

	public java.lang.Integer getService_id() {
		return this.service_id;
	}

	public void setService_id(java.lang.Integer service_id) {
		this.service_id = service_id;
	}

	public java.util.Date getApplication_date() {
		return this.application_date;
	}

	public void setApplication_date(java.util.Date application_date) {
		this.application_date = application_date;
	}

	public java.math.BigDecimal getSettlement_amount() {
		return this.settlement_amount;
	}

	public void setSettlement_amount(java.math.BigDecimal settlement_amount) {
		this.settlement_amount = settlement_amount;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getWorkflow_status() {
		return this.workflow_status;
	}

	public void setWorkflow_status(java.lang.String workflow_status) {
		this.workflow_status = workflow_status;
	}

	public java.lang.Long getBuyer_id() {
		return this.buyer_id;
	}

	public void setBuyer_id(java.lang.Long buyer_id) {
		this.buyer_id = buyer_id;
	}

	public java.lang.Long getSeller_id() {
		return this.seller_id;
	}

	public void setSeller_id(java.lang.Long seller_id) {
		this.seller_id = seller_id;
	}

	public java.lang.Long getProperty_id() {
		return this.property_id;
	}

	public void setProperty_id(java.lang.Long property_id) {
		this.property_id = property_id;
	}

	public java.lang.Long getNotary_id() {
		return this.notary_id;
	}

	public void setNotary_id(java.lang.Long notary_id) {
		this.notary_id = notary_id;
	}

	public java.lang.String getPayment_status() {
		return this.payment_status;
	}

	public void setPayment_status(java.lang.String payment_status) {
		this.payment_status = payment_status;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Transaction [service_id=" + service_id + ", application_date="
				+ application_date + ", settlement_date=" + settlement_date
				+ ", settlement_amount=" + settlement_amount + ", status="
				+ status + ", workflow_status=" + workflow_status
				+ ", buyer_id=" + buyer_id + ", seller_id=" + seller_id
				+ ", property_id=" + property_id + ", payment_status="
				+ payment_status + ", id=" + id + ", notary=" + notary + "]";
	}

	public com.dhh.landservices.Notary getNotary() {
		return this.notary;
	}

	public void setNotary(com.dhh.landservices.Notary notary) {
		this.notary = notary;
	}

	public java.util.Date getSettlement_date() {
		return this.settlement_date;
	}

	public void setSettlement_date(java.util.Date settlement_date) {
		this.settlement_date = settlement_date;
	}

	public Transaction(java.lang.Integer service_id,
			java.util.Date application_date,
			java.math.BigDecimal settlement_amount, java.lang.String status,
			java.lang.String workflow_status, java.lang.Long buyer_id,
			java.lang.Long seller_id, java.lang.Long property_id,
			java.lang.Long notary_id, java.lang.String payment_status,
			java.lang.Long id, com.dhh.landservices.Notary notary,
			java.util.Date settlement_date) {
		this.service_id = service_id;
		this.application_date = application_date;
		this.settlement_amount = settlement_amount;
		this.status = status;
		this.workflow_status = workflow_status;
		this.buyer_id = buyer_id;
		this.seller_id = seller_id;
		this.property_id = property_id;
		this.notary_id = notary_id;
		this.payment_status = payment_status;
		this.id = id;
		this.notary = notary;
		this.settlement_date = settlement_date;
	}

}